"use client";
//import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ApolloProvider } from '@apollo/client';
import client from "@/components/apollo-client/apollo-client";
import { usePathname } from 'next/navigation'
import AuthenticationLayout from "@/components/layout/authentication-layout";
import ManagementLayout from "@/components/layout/management-layout";
import { AUTHENTICATION_LAYOUT_PAGES } from "@/utils/consts";
import PageTitleContextProvider from "@/components/contexts/page-title-context";
import AuthContextProvider from "@/components/contexts/auth-context";
import ResponsiveContextProvider from "@/components/contexts/responsive-context";
import TenantContextProvider from "@/components/contexts/tenant-context";
import ManagementTenantFilter from "@/components/contexts/management-tenant-filter";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "OIDC Authentication Provider",
//   description: "Generated by create next app",
// };



export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {



    const pathName = usePathname();
    const isAuthenticationLayoutPage: boolean = AUTHENTICATION_LAYOUT_PAGES.includes(pathName || "");

    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <ApolloProvider client={client}>
                    <ResponsiveContextProvider>
                        <PageTitleContextProvider>
                            {isAuthenticationLayoutPage &&
                                <AuthenticationLayout>{children}</AuthenticationLayout>
                            }
                            {!isAuthenticationLayoutPage &&
                                <AuthContextProvider>
                                    <TenantContextProvider>
                                        <ManagementTenantFilter>
                                            <ManagementLayout>{children}</ManagementLayout>
                                        </ManagementTenantFilter>
                                    </TenantContextProvider>
                                </AuthContextProvider>
                            }
                        </PageTitleContextProvider>
                    </ResponsiveContextProvider>
                </ApolloProvider>
            </body>
        </html>
    );
}
