"use client";
import { Button, DialogActions, DialogContent, Grid2, Typography } from "@mui/material";
import React from "react";
import RadioStyledCheckbox from "../input/radio-styled-checkbox";
import NewAutoGeneratedSigningKeyDialog from "./new-autogenerated-key-dialog";
import NewBroughtMyOwnSigningKeyDialog from "./new-brought-my-own-signing-key-dialog";


export interface NewSigningKeyDialogProps {
    tenantId: string,
    onCancel: () => void,
    onClose: () => void,
    onCreateStart: () => void,
    onCreateEnd: (success: boolean) => void
}

const NewSigningKeyDialog: React.FC<NewSigningKeyDialogProps> = ({
    tenantId,
    onCancel,
    onClose,
    onCreateEnd,
    onCreateStart
}) => {

    const [dialogType, setDialogType] = React.useState<string | null>(null);
    const [dialogTypeSelected, setDialogTypeSelected] = React.useState<string | null>(null);

    return (
        <React.Fragment>
            {dialogType === null &&
                <React.Fragment>                    
                    <DialogContent>
                        <Typography component={"div"}>                    
                            <Grid2 container size={12} spacing={0} marginBottom={"16px"} >
                                <Grid2 marginBottom={"16px"} fontWeight={"bold"} size={12}>How do you want to create a new key?</Grid2>
                                
                                <Grid2 size={11}>I brought my own key</Grid2>
                                <Grid2 size={1}>
                                    <RadioStyledCheckbox 
                                        checked={dialogTypeSelected === "BROUGHT_MY_OWN"}
                                        onChange={(_, checked: boolean) => {
                                            if(checked && dialogTypeSelected !== "BROUGHT_MY_OWN"){
                                                setDialogTypeSelected("BROUGHT_MY_OWN");
                                            }
                                        }}
                                    />
                                </Grid2>
                                <Grid2 size={11}>Let the system auto-generate the key</Grid2>
                                <Grid2 size={1}>
                                    <RadioStyledCheckbox 
                                        checked={dialogTypeSelected === "AUTO_GENERATED"}
                                        onChange={(_, checked: boolean) => {
                                            if(checked && dialogTypeSelected !== "AUTO_GENERATED"){
                                                setDialogTypeSelected("AUTO_GENERATED");
                                            }
                                        }}
                                    />
                                </Grid2>
                            </Grid2>
                        </Typography>
                    </DialogContent>

                    <DialogActions>
                        <Button onClick={() => { onCancel(); }}>Cancel</Button>
                        <Button
                            disabled={dialogTypeSelected === null}
                            onClick={() => setDialogType(dialogTypeSelected)}
                        >
                            Next
                        </Button>
                    </DialogActions>
                </React.Fragment>
            }
            {dialogType === "BROUGHT_MY_OWN" &&
                <NewBroughtMyOwnSigningKeyDialog
                    tenantId={tenantId}
                    onCancel={onCancel}
                    onClose={onClose}
                    onCreateEnd={onCreateEnd}
                    onCreateStart={onCreateStart}
                />
            }
            {dialogType === "AUTO_GENERATED" &&
                <NewAutoGeneratedSigningKeyDialog
                    tenantId={tenantId}
                    onCancel={onCancel}
                    onClose={onClose}
                    onCreateEnd={onCreateEnd}
                    onCreateStart={onCreateStart}
                />
            }
        </React.Fragment>            
        
    )

}

export default NewSigningKeyDialog;
