"use client";
import { SigningKeyCreateInput } from "@/graphql/generated/graphql-types";
import { SIGNING_KEY_CREATE_MUTATION } from "@/graphql/mutations/oidc-mutations";
import { CERTIFICATE_HEADER, KEY_TYPE_EC, KEY_TYPE_RSA, KEY_USE_CERTIFICATE_SIGNING, KEY_USE_DIGITAL_SIGNING, KEY_USE_DISPLAY, KEY_USE_ENCRYPTION, KEY_USE_KEY_AGREEMENT, MIN_PRIVATE_KEY_PASSWORD_LENGTH, PKCS8_ENCRYPTED_PRIVATE_KEY_HEADER, PKCS8_PRIVATE_KEY_HEADER, PKCS8_PUBLIC_KEY_HEADER } from "@/utils/consts";
import { useMutation } from "@apollo/client";
import { Alert, Button, DialogActions, DialogContent, Grid2, MenuItem, Select, Stack, TextField, Typography } from "@mui/material";
import React, { useContext } from "react";
import { TenantMetaDataBean, TenantContext } from "../contexts/tenant-context";
import { useRouter } from 'next/navigation';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { PickerValue } from "@mui/x-date-pickers/internals";
import RadioStyledCheckbox from "../input/radio-styled-checkbox";
import NewAutoGeneratedSigningKeyDialog from "./new-autogenerated-key-dialog";
import NewBroughtMyOwnSigningKeyDialog from "./new-brought-my-own-signing-key-dialog";


export interface NewSigningKeyDialogProps {
    tenantId: string,
    onCancel: () => void,
    onClose: () => void,
    onCreateStart: () => void,
    onCreateEnd: (success: boolean) => void
}

const NewSigningKeyDialog: React.FC<NewSigningKeyDialogProps> = ({
    tenantId,
    onCancel,
    onClose,
    onCreateEnd,
    onCreateStart
}) => {

    const [dialogType, setDialogType] = React.useState<string | null>(null);
    const [dialogTypeSelected, setDialogTypeSelected] = React.useState<string | null>(null);

    return (
        <React.Fragment>
            {dialogType === null &&
                <React.Fragment>                    
                    <DialogContent>
                        <Typography component={"div"}>                    
                            <Grid2 container size={12} spacing={0} marginBottom={"16px"} >
                                <Grid2 marginBottom={"16px"} fontWeight={"bold"} size={12}>How do you want to create a new key?</Grid2>
                                
                                <Grid2 size={11}>I brought my own key</Grid2>
                                <Grid2 size={1}>
                                    <RadioStyledCheckbox 
                                        checked={dialogTypeSelected === "BROUGHT_MY_OWN"}
                                        onChange={(_, checked: boolean) => {
                                            if(checked && dialogTypeSelected !== "BROUGHT_MY_OWN"){
                                                setDialogTypeSelected("BROUGHT_MY_OWN");
                                            }
                                        }}
                                    />
                                </Grid2>
                                <Grid2 size={11}>Let the system auto-generate the key</Grid2>
                                <Grid2 size={1}>
                                    <RadioStyledCheckbox 
                                        checked={dialogTypeSelected === "AUTO_GENERATED"}
                                        onChange={(_, checked: boolean) => {
                                            if(checked && dialogTypeSelected !== "AUTO_GENERATED"){
                                                setDialogTypeSelected("AUTO_GENERATED");
                                            }
                                        }}
                                    />
                                </Grid2>
                            </Grid2>
                        </Typography>
                    </DialogContent>

                    <DialogActions>
                        <Button onClick={() => { onCancel(); }}>Cancel</Button>
                        <Button
                            disabled={dialogTypeSelected === null}
                            onClick={() => setDialogType(dialogTypeSelected)}
                        >
                            Next
                        </Button>
                    </DialogActions>
                </React.Fragment>
            }
            {dialogType === "BROUGHT_MY_OWN" &&
                <NewBroughtMyOwnSigningKeyDialog
                    tenantId={tenantId}
                    onCancel={onCancel}
                    onClose={onClose}
                    onCreateEnd={onCreateEnd}
                    onCreateStart={onCreateStart}
                />
            }
            {dialogType === "AUTO_GENERATED" &&
                <NewAutoGeneratedSigningKeyDialog
                    tenantId={tenantId}
                    onCancel={onCancel}
                    onClose={onClose}
                    onCreateEnd={onCreateEnd}
                    onCreateStart={onCreateStart}
                />
            }
        </React.Fragment>            
        
    )

}

export default NewSigningKeyDialog;
