"use client";
import { AutoCreateSigningKeyInput } from "@/graphql/generated/graphql-types";
import { AUTO_GENERATE_SIGNING_KEY_CREATE_MUTATION } from "@/graphql/mutations/oidc-mutations";
import { KEY_TYPE_RSA, KEY_USE_CERTIFICATE_SIGNING, KEY_USE_DIGITAL_SIGNING, KEY_USE_DISPLAY, KEY_USE_ENCRYPTION, KEY_USE_KEY_AGREEMENT, MIN_PRIVATE_KEY_PASSWORD_LENGTH } from "@/utils/consts";
import { useMutation } from "@apollo/client";
import { Alert, Button, DialogActions, DialogContent, Grid2, MenuItem, Select, Stack, TextField, Typography } from "@mui/material";
import React, { useContext } from "react";
import { TenantMetaDataBean, TenantContext } from "../contexts/tenant-context";
import { useRouter } from 'next/navigation';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { PickerValue } from "@mui/x-date-pickers/internals";


export interface NewSigningKeyDialogProps {
    tenantId: string,
    onCancel: () => void,
    onClose: () => void,
    onCreateStart: () => void,
    onCreateEnd: (success: boolean) => void
}

const NewAutoGeneratedSigningKeyDialog: React.FC<NewSigningKeyDialogProps> = ({
    tenantId,
    onCancel,
    onClose,
    onCreateEnd,
    onCreateStart
}) => {

    const initInput: AutoCreateSigningKeyInput = {
        tenantId: tenantId,
        keyType: KEY_TYPE_RSA,
        keyTypeId: "",
        commonName: "",
        organizationName: "",
        keyName: "",
        keyUse: "",
        password: "",
        expiresAtMs: 0
    }

    // HOOKS
    const router = useRouter();

    // CONTEXT
    const tenantBean: TenantMetaDataBean = useContext(TenantContext);

    // STATE VARIABLES    
    const [signingKeyInput, setSigningKeyInput] = React.useState<AutoCreateSigningKeyInput>(initInput);
    const [errorMessage, setErrorMessage] = React.useState<string | null>(null);
    const [publicExpDateValid, setPublicKeyExpDateValid] = React.useState<boolean>(false);   


    // GRAPHQL FUNCTIONS
    const [createSigningKeyMutation] = useMutation(
        AUTO_GENERATE_SIGNING_KEY_CREATE_MUTATION,
        {
            variables: {
                keyInput: signingKeyInput
            },
            onCompleted(data) {
                onCreateEnd(true);                
                router.push(`/${tenantBean.getTenantMetaData().tenant.tenantId}/signing-keys/${data.autoCreateSigningKey.keyId}`);
                onClose();
            },
            onError(error) {
                onCreateEnd(false);
                setErrorMessage(error.message);
            }            
        }
    );


    const isValidInput = (signingKey: AutoCreateSigningKeyInput): boolean => {
        if(signingKey.keyName === ""){
            return false;
        }

        // Only allow 365 days maximum for a signing key
        if(publicExpDateValid === false){
            return false;
        }
        if(signingKey.keyType === ""){
            return false;
        }
        if(signingKey.keyUse === ""){
            return false;
        }
        if(signingKey.commonName === ""){
            return false;
        }
        if(signingKey.organizationName === ""){
            return false;
        }
        if(signingKey.password && signingKey.password !== "" && signingKey.password.length < MIN_PRIVATE_KEY_PASSWORD_LENGTH){
            return false;
        }
        return true;
    }


    return (
        <>
            <DialogContent>
                <LocalizationProvider dateAdapter={AdapterDayjs}>
                    <Typography component={"div"}>                    
                        <Grid2 container size={12} spacing={3} marginBottom={"16px"} >
                            <Grid2 size={12}>
                                {errorMessage &&
                                    <Grid2 size={{ xs: 12 }} textAlign={"center"}>
                                        <Stack
                                            direction={"row"}
                                            justifyItems={"center"}
                                            alignItems={"center"}
                                            sx={{ width: "100%" }}
                                        >
                                            <Alert onClose={() => setErrorMessage(null)} sx={{ width: "100%" }} severity="error">{errorMessage}</Alert>
                                        </Stack>
                                    </Grid2>
                                }
                                <Grid2 marginBottom={"16px"}>
                                    <div>Key Name / Alias</div>
                                    <TextField
                                        required name="keyNameAlias" id="keyNameAlias"
                                        onChange={(evt) => { signingKeyInput.keyName = evt?.target.value; setSigningKeyInput({ ...signingKeyInput }); }}
                                        value={signingKeyInput.keyName}
                                        fullWidth={true}
                                        size="small" />
                                </Grid2>
                                <Grid2 marginBottom={"16px"}>
                                    <div>Key Type</div>
                                    <Select
                                        size="small"
                                        fullWidth={true}
                                        value={signingKeyInput.keyType}
                                        name="keyType"
                                        onChange={(evt) => {
                                            signingKeyInput.keyType = evt.target.value;                                        
                                            setSigningKeyInput({ ...signingKeyInput });
                                        }}
                                    >
                                        <MenuItem value={KEY_TYPE_RSA} >{KEY_TYPE_RSA}</MenuItem>                                     
                                    </Select>                                
                                </Grid2>
                                <Grid2 marginBottom={"16px"}>
                                    <div>Key Use</div>
                                    <Select
                                        size="small"
                                        fullWidth={true}
                                        value={signingKeyInput.keyUse}
                                        name="keyUse"
                                        onChange={(evt) => {
                                            signingKeyInput.keyUse = evt.target.value;                                        
                                            setSigningKeyInput({ ...signingKeyInput });
                                        }}
                                    >
                                        <MenuItem value={""}>Select Key Use</MenuItem>
                                        <MenuItem value={KEY_USE_DIGITAL_SIGNING} >{KEY_USE_DISPLAY.get(KEY_USE_DIGITAL_SIGNING)}</MenuItem>
                                        <MenuItem value={KEY_USE_ENCRYPTION} >{KEY_USE_DISPLAY.get(KEY_USE_ENCRYPTION)}</MenuItem>
                                        <MenuItem value={KEY_USE_KEY_AGREEMENT} >{KEY_USE_DISPLAY.get(KEY_USE_KEY_AGREEMENT)}</MenuItem>
                                        <MenuItem value={KEY_USE_CERTIFICATE_SIGNING} >{KEY_USE_DISPLAY.get(KEY_USE_CERTIFICATE_SIGNING)}</MenuItem>
                                    </Select>                                
                                </Grid2>
                                <Grid2 marginBottom={"16px"}>
                                    <div>Common Name (CN)</div>
                                    <TextField
                                        required name="commonName" id="commonName"
                                        onChange={(evt) => { signingKeyInput.commonName = evt?.target.value; setSigningKeyInput({ ...signingKeyInput }); }}
                                        value={signingKeyInput.commonName}
                                        fullWidth={true}
                                        size="small" />
                                </Grid2>
                                <Grid2 marginBottom={"16px"}>
                                    <div>Organization Name (O)</div>
                                    <TextField
                                        required
                                        name="organizationName" id="organizationName"
                                        onChange={(evt) => { signingKeyInput.organizationName = evt?.target.value; setSigningKeyInput({ ...signingKeyInput }); }}
                                        value={signingKeyInput.organizationName}
                                        fullWidth={true}
                                        size="small" />
                                </Grid2>
                                <Grid2 marginBottom={"16px"}>
                                    <div>Passphrase (Minimum length 16 characters. If omitted the system will generate one.)</div>
                                    <TextField
                                        required={false}
                                        name="keyPassphrase" 
                                        id="keyPassphrase"
                                        onChange={(evt) => { 
                                            signingKeyInput.password = evt?.target.value; 
                                            setSigningKeyInput({ ...signingKeyInput }); 
                                        }}
                                        value={signingKeyInput.password}
                                        fullWidth={true}                                    
                                        size="small" 
                                        type="password"
                                    />
                                </Grid2>                                 
                                <Grid2 marginBottom={"16px"}>
                                    <div>Expires (Maximum of 1 year)</div>
                                    <DatePicker                                             
                                        slotProps={
                                            { textField: { size: "small" }}
                                        }                                            
                                        onChange={(value: PickerValue) => {
                                            if(value){
                                                const expTime: number = value?.toDate().getTime();
                                                const now: number = new Date().getTime();                                                    
                                                const diff: number = expTime - now;
                                                // if not negative or less than a year, then
                                                if(diff > 0 && diff < 31557600000){
                                                    signingKeyInput.expiresAtMs = expTime;
                                                    setSigningKeyInput({ ...signingKeyInput });
                                                    setPublicKeyExpDateValid(true);
                                                }
                                                else{
                                                    setPublicKeyExpDateValid(false);
                                                }
                                            }
                                        }}                                            
                                    />
                                </Grid2>                                                                
                            </Grid2>
                        </Grid2>
                    </Typography>
                </LocalizationProvider>
            </DialogContent>
            <DialogActions>
                <Button onClick={() => { onCancel(); }}>Cancel</Button>
                <Button
                    onClick={() => {
                        onCreateStart();
                        createSigningKeyMutation();
                    }}
                    disabled={
                        !isValidInput(signingKeyInput)
                    }
                >
                    Create
                </Button>
            </DialogActions>

        </>
    )
}

export default NewAutoGeneratedSigningKeyDialog;